"""add steps_tss to trainingsession

Revision ID: 304f9ccbcf15
Revises: 73a1130e2fc8
Create Date: 2026-04-16 09:46:43.303086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '304f9ccbcf15'
down_revision: Union[str, Sequence[str], None] = '73a1130e2fc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trainingsession', sa.Column('steps_tss', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trainingsession', 'steps_tss')
    # ### end Alembic commands ###
