"""add_icu_event_id_to_trainingsession

Revision ID: 573a4aff37d9
Revises: e35d6b485acf
Create Date: 2026-04-15 00:02:43.746770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '573a4aff37d9'
down_revision: Union[str, Sequence[str], None] = 'e35d6b485acf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trainingsession', sa.Column('icu_event_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trainingsession', 'icu_event_id')
    # ### end Alembic commands ###
