"""add activity_id to trainingsession

Revision ID: 73a1130e2fc8
Revises: 80effe9b74af
Create Date: 2026-04-15 16:17:14.398602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '73a1130e2fc8'
down_revision: Union[str, Sequence[str], None] = '80effe9b74af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trainingsession', sa.Column('activity_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_trainingsession_activity_id'), 'trainingsession', ['activity_id'], unique=False)
    op.create_foreign_key(None, 'trainingsession', 'activity', ['activity_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trainingsession', type_='foreignkey')
    op.drop_index(op.f('ix_trainingsession_activity_id'), table_name='trainingsession')
    op.drop_column('trainingsession', 'activity_id')
    # ### end Alembic commands ###
