"""add icu_compliance to trainingsession

Revision ID: 80effe9b74af
Revises: 573a4aff37d9
Create Date: 2026-04-15 14:09:05.197461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '80effe9b74af'
down_revision: Union[str, Sequence[str], None] = '573a4aff37d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trainingsession', sa.Column('icu_compliance', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trainingsession', 'icu_compliance')
    # ### end Alembic commands ###
