"""drop_goal_plan_tables

Revision ID: 8f2751cba3d3
Revises: 304f9ccbcf15
Create Date: 2026-04-20 18:50:52.945502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8f2751cba3d3'
down_revision: Union[str, Sequence[str], None] = '304f9ccbcf15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.drop_index(op.f('ix_trainingsession_activity_id'), table_name='trainingsession')
    op.drop_index(op.f('ix_trainingsession_week_id'), table_name='trainingsession')
    op.drop_table('trainingsession')
    op.drop_index(op.f('ix_trainingweek_plan_id'), table_name='trainingweek')
    op.drop_table('trainingweek')
    op.drop_index(op.f('ix_trainingplan_goal_id'), table_name='trainingplan')
    op.drop_table('trainingplan')
    op.drop_table('goal')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trainingplan',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('goal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('summary', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('rationale', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['goal.id'], name=op.f('trainingplan_goal_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('trainingplan_pkey'))
    )
    op.create_index(op.f('ix_trainingplan_goal_id'), 'trainingplan', ['goal_id'], unique=False)
    op.create_table('goal',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('goal_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('target_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('target_ftp', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('goal_pkey'))
    )
    op.create_table('trainingsession',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('week_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('day_of_week', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('session_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tss_target', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('duration_min', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('steps', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('icu_event_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('icu_compliance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('activity_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('steps_tss', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], name=op.f('trainingsession_activity_id_fkey')),
    sa.ForeignKeyConstraint(['week_id'], ['trainingweek.id'], name=op.f('trainingsession_week_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('trainingsession_pkey'))
    )
    op.create_index(op.f('ix_trainingsession_week_id'), 'trainingsession', ['week_id'], unique=False)
    op.create_index(op.f('ix_trainingsession_activity_id'), 'trainingsession', ['activity_id'], unique=False)
    op.create_table('trainingweek',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('week_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('phase', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tss_target', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('week_start', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('stale', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('week_type', sa.VARCHAR(), server_default=sa.text("'a'::character varying"), autoincrement=False, nullable=False),
    sa.Column('avail_override', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['trainingplan.id'], name=op.f('trainingweek_plan_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('trainingweek_pkey'))
    )
    op.create_index(op.f('ix_trainingweek_plan_id'), 'trainingweek', ['plan_id'], unique=False)
    # ### end Alembic commands ###
