"""add rpe feel notes

Revision ID: a9dc85782eb0
Revises: c5748495dc29
Create Date: 2026-02-22 13:54:55.176349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a9dc85782eb0'
down_revision: Union[str, Sequence[str], None] = 'c5748495dc29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('icu_rpe', sa.Integer(), nullable=True))
    op.add_column('activity', sa.Column('feel', sa.Integer(), nullable=True))
    op.add_column('activity', sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity', 'notes')
    op.drop_column('activity', 'feel')
    op.drop_column('activity', 'icu_rpe')
    # ### end Alembic commands ###
