"""training_week_stale

Revision ID: b9eb4c151b35
Revises: f6a1b2c3d4e5
Create Date: 2026-04-07 09:11:21.871586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b9eb4c151b35'
down_revision: Union[str, Sequence[str], None] = 'f6a1b2c3d4e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('trainingweek', sa.Column('week_start', sa.Date(), nullable=True))
    op.add_column('trainingweek', sa.Column('stale', sa.Boolean(), nullable=False, server_default=sa.false()))

    # Backfill week_start from the parent plan's generated_at date
    conn = op.get_bind()
    rows = conn.execute(sa.text(
        "SELECT tw.id, tw.week_number, tp.generated_at "
        "FROM trainingweek tw JOIN trainingplan tp ON tp.id = tw.plan_id"
    )).fetchall()
    for row in rows:
        generated_at = row[2].date() if hasattr(row[2], 'date') else row[2]
        plan_monday = generated_at - __import__('datetime').timedelta(days=generated_at.weekday())
        week_start = plan_monday + __import__('datetime').timedelta(weeks=row[1] - 1)
        conn.execute(
            sa.text("UPDATE trainingweek SET week_start = :ws WHERE id = :id"),
            {"ws": week_start, "id": row[0]},
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trainingweek', 'stale')
    op.drop_column('trainingweek', 'week_start')
    # ### end Alembic commands ###
