"""initial

Revision ID: c5748495dc29
Revises: 
Create Date: 2026-02-22 13:31:04.563073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c5748495dc29'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('icu_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('athlete_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sport', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.Column('moving_time', sa.Integer(), nullable=True),
    sa.Column('elapsed_time', sa.Integer(), nullable=True),
    sa.Column('total_elevation_gain', sa.Float(), nullable=True),
    sa.Column('average_watts', sa.Float(), nullable=True),
    sa.Column('normalized_watts', sa.Float(), nullable=True),
    sa.Column('max_watts', sa.Integer(), nullable=True),
    sa.Column('weighted_average_watts', sa.Float(), nullable=True),
    sa.Column('average_heartrate', sa.Float(), nullable=True),
    sa.Column('max_heartrate', sa.Integer(), nullable=True),
    sa.Column('average_cadence', sa.Float(), nullable=True),
    sa.Column('average_speed', sa.Float(), nullable=True),
    sa.Column('max_speed', sa.Float(), nullable=True),
    sa.Column('tss', sa.Float(), nullable=True),
    sa.Column('intensity_factor', sa.Float(), nullable=True),
    sa.Column('icu_training_load', sa.Float(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_athlete_id'), 'activity', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_activity_icu_id'), 'activity', ['icu_id'], unique=True)
    op.create_index(op.f('ix_activity_sport'), 'activity', ['sport'], unique=False)
    op.create_index(op.f('ix_activity_start_date'), 'activity', ['start_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activity_start_date'), table_name='activity')
    op.drop_index(op.f('ix_activity_sport'), table_name='activity')
    op.drop_index(op.f('ix_activity_icu_id'), table_name='activity')
    op.drop_index(op.f('ix_activity_athlete_id'), table_name='activity')
    op.drop_table('activity')
    # ### end Alembic commands ###
