"""plan_owned_availability

Revision ID: e35d6b485acf
Revises: b9eb4c151b35
Create Date: 2026-04-07 11:51:44.962592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e35d6b485acf'
down_revision: Union[str, Sequence[str], None] = 'b9eb4c151b35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_availabilityweek_week_start'), table_name='availabilityweek')
    op.drop_table('availabilityweek')
    op.add_column('trainingplan', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('trainingweek', sa.Column('week_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='a'))
    op.add_column('trainingweek', sa.Column('avail_override', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trainingweek', 'avail_override')
    op.drop_column('trainingweek', 'week_type')
    op.drop_column('trainingplan', 'start_date')
    op.create_table('availabilityweek',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('week_start', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('week_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hours', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('availabilityweek_pkey'))
    )
    op.create_index(op.f('ix_availabilityweek_week_start'), 'availabilityweek', ['week_start'], unique=True)
    # ### end Alembic commands ###
